Repository SuSang-YuHee/Debate-Ducks-Client, pull requests merged in 2022-08, with the labels that each got.

#63 토론 게시물 제목, 토론자, 좋아요, 팩트체크 및 토론 카드 수정
  components/common/modal/ConfirmModal.module.scss
  components/common/modal/SignInModal.module.scss
  components/debates/CreateOrEdit.module.scss
  components/debates/CreateOrEdit.tsx
  components/debates/DebaterInfo.module.scss
  components/debates/DebaterInfo.tsx
  components/debates/debate/AfterDebate.tsx
  components/debates/debate/DebaterInfo.tsx
  components/debates/debate/EditAndDelete.module.scss
  components/debates/debate/EditAndDelete.tsx
  components/debates/debate/Factcheck.tsx
  components/debates/debate/Factchecks.module.scss
  components/debates/debate/Factchecks.tsx
  components/debates/debate/index.module.scss
  components/debates/debate/index.tsx
  components/debates/debates/DebateCard.module.scss
  components/debates/debates/DebateCard.tsx
  components/debates/debates/Debater.tsx
  components/debates/debates/DebatesCards.module.scss
  components/debates/debates/DebatesCards.tsx
  components/debates/debates/DebatesHeartList.tsx
  components/debates/debates/DebatesList.tsx
  components/debates/debates/Filters.module.scss
  components/debates/debates/LikeBtn.module.scss
  pages/_app.tsx
  pages/debates/[debateId].tsx
  pages/debates/create.tsx
  pages/debates/edit/[debateId].tsx
  pages/debates/index.tsx
  styles/variable.scss
  utils/common/formatStrDate.ts
  utils/queries/debates.ts
Labels: Modify, Delete, Change, Update, Fix, Style

#64 투표 기능 업데이트 및 스타일 추가
  components/debates/CreateOrEdit.module.scss
  components/debates/debate/AfterDebate.tsx
  components/debates/debate/Factcheck.tsx
  components/debates/debate/Factchecks.module.scss
  components/debates/debate/Vote.module.scss
  components/debates/debate/Vote.tsx
  components/debates/debate/index.module.scss
  components/debates/debate/index.tsx
  components/debates/debates/DebateCard.tsx
  components/debates/debates/DebatesCards.module.scss
  utils/common/thousandDigit.ts
Labels: Update, Fix, Style

#67 댓글 기능 개선 및 스타일 작업 & 빌드시 타입 에러 해결
  components/debates/DebaterInfo.module.scss
  components/debates/debate/Comments.module.scss
  components/debates/debate/Comments.tsx
  components/debates/debate/Factcheck.tsx
  components/debates/debate/Factchecks.tsx
  components/debates/debate/Vote.module.scss
  components/debates/debate/index.module.scss
  components/debates/debate/index.tsx
  styles/variable.scss
  types.ts
  utils/common/constant.ts
  utils/queries/debates.ts
  utils/queries/factchecks.ts
  utils/queries/hearts.ts
  utils/queries/votes.ts
Labels: Modify, Delete, Change, Update, Fix, Style

#68 빌드 시 발생하는 에러 해결
  next.config.js
  package-lock.json
  package.json
  pages/debates/[debateId].tsx
  pages/debates/edit/[debateId].tsx
  pages/mypage/index.tsx
Labels: Modify, Add, Delete

#69 빌드 스크립트 변경
  package.json
Labels: Change

#74 Hotfix/simple modify and fix
  api/users.ts
  components/common/modal/ConfirmModal.module.scss
  components/common/modal/SignInModal.module.scss
  components/debates/DebaterInfo.tsx
  components/debates/debate/Comments.tsx
  components/debates/debate/index.module.scss
  components/debates/debates/DebateCard.module.scss
  components/debates/debates/DebateCard.tsx
  utils/common/constant.ts
  utils/queries/users.ts
Labels: Modify, Change, Fix, Style

#75 토론 페이지를 메인 페이지로 대체
  components/debates/debates/DebateCard.tsx
  components/debates/debates/DebatesCards.tsx
  pages/[debateId].tsx
  pages/create.tsx
  pages/debateroom/[debateId].tsx
  pages/debates/index.tsx
  pages/edit/[debateId].tsx
  pages/index.tsx
  utils/queries/debates.ts
Labels: Modify

#77 참여하기 추가
  components/debates/debate/index.module.scss
  components/debates/debate/index.tsx
Labels: Update, Style

#78 홈 및 탑 버튼 추가
  components/common/btn/HomeAndTopBtn.module.scss
  components/common/btn/HomeAndTopBtn.tsx
  components/debates/debate/index.tsx
  pages/index.tsx
Labels: Add, Update, Style

#79 프로필 이미지 테두리 추가
  components/common/btn/HomeAndTopBtn.tsx
  components/debates/DebaterInfo.module.scss
  components/debates/DebaterInfo.tsx
  components/debates/debate/Comments.module.scss
  components/debates/debate/Comments.tsx
  components/debates/debate/EditAndDelete.tsx
  components/debates/debate/index.tsx
Labels: Modify, Update, Fix, Style

#82 마이페이지 미디어 쿼리 추가
  pages/mypage/MyPage.module.scss
Labels: Style

#83 로그인 페이지 스타일링
  pages/signin/Signin.module.scss
  pages/signin/index.tsx
Labels: Style

#84 실시간 토론방 에러 해결, 개선 및 스타일 적용
  components/common/modal/ConfirmModal.module.scss
  components/common/modal/ConfirmModal.tsx
  components/debates/CreateOrEdit.tsx
  components/debates/DebaterInfo.tsx
  components/debates/debate/Comments.tsx
  components/debates/debate/index.module.scss
  components/debates/debate/index.tsx
  components/debates/debateroom/Buttons.module.scss
  components/debates/debateroom/Buttons.tsx
  components/debates/debateroom/Canvas.module.scss
  components/debates/debateroom/Canvas.tsx
  components/debates/debateroom/index.tsx
  components/debates/debateroom/types.ts
  components/debates/debateroom/utils/toggle.ts
  components/debates/debateroom/utils/upload.ts
  components/debates/debates/DebatesCards.tsx
  next.config.js
  pages/_app.tsx
  pages/debateroom/[debateId].tsx
  types.ts
  utils/debates/debateroom/beep.ts
  utils/debates/debateroom/draw.ts
  utils/debates/debateroom/screenShare.ts
  utils/debates/debateroom/simple-peer.ts
  utils/debates/debateroom/toggle.ts
  utils/debates/debateroom/useAutoOff.ts
  utils/debates/debateroom/usePreventBack.ts
  utils/debates/debateroom/useSetInterval.ts
  utils/debates/debateroom/useSetRecorder.ts
  utils/debates/debateroom/webSocket.ts
Labels: Modify, Add, Delete, Change, Update, Fix, Style

#85 회원가입 비밀번호 확인 추가 및 스타일링
  api/users.ts
  pages/signup/Signup.module.scss
  pages/signup/index.tsx
  styles/Signup.module.scss
  types.ts
Labels: Update, Style

#86 로그인 요청 수정 및 스타일링
  pages/signin/Signin.module.scss
  pages/signin/index.tsx
Labels: Update

#88 유저 프로필 디폴트 이미지 설정
  components/Header.tsx
  pages/mypage/index.tsx
  public/images/profiles/default-green.png
Labels: Update

#89 녹화 영상 s3 업로드 기능 추가
  components/debates/DebaterInfo.tsx
  components/debates/debate/Comments.tsx
  components/debates/debateroom/index.tsx
  components/debates/debates/DebatesCards.tsx
  package-lock.json
  package.json
  utils/debates/debateroom/aws.ts
  utils/debates/debateroom/webSocket.ts
  utils/queries/debates.ts
Labels: Add, Change, Update, Setting

#97 헤더 개선 및 기타 에러 해결
  components/Header.module.scss
  components/Header.tsx
  components/common/modal/ChangePasswordModal.module.scss
  components/common/modal/ConfirmModal.module.scss
  components/common/modal/SignInModal.module.scss
  components/debates/CreateOrEdit.module.scss
  components/debates/debate/Factcheck.tsx
  components/debates/debate/Factchecks.module.scss
  components/debates/debate/Vote.module.scss
  components/debates/debate/Vote.tsx
  components/debates/debate/index.module.scss
  components/debates/debate/index.tsx
  components/debates/debates/DebateCard.tsx
  components/debates/debates/DebatesCards.module.scss
  components/debates/debates/Filters.module.scss
  components/debates/debates/LikeBtn.module.scss
  pages/q&a/index.tsx
Labels: Add, Update, Fix, Style

#98 로그인 및 회원가입 개선
  components/Header.module.scss
  components/Header.tsx
  pages/_app.tsx
  pages/signin/index.tsx
  pages/signup/index.tsx
Labels: Add, Update, Style

#99 토론 목록 상태관리 리덕스 사용
  api/users.ts
  components/Header.module.scss
  components/common/modal/ChangePasswordModal.tsx
  components/common/modal/CheckSignInModal.tsx
  components/common/modal/SignInModal.module.scss
  components/common/modal/SignInModal.tsx
  components/debates/debates/DebatesCards.tsx
  components/debates/debates/DebatesHeartList.tsx
  components/debates/debates/DebatesList.tsx
  components/debates/debates/Filters.tsx
  components/debates/debates/LikeBtn.tsx
  package-lock.json
  package.json
  pages/_app.tsx
  pages/index.tsx
  pages/mypage/index.tsx
  redux/modules/categories.ts
  redux/modules/heartOrder.ts
  redux/modules/isHeartListOn.ts
  redux/modules/isSearchListOn.ts
  redux/modules/order.ts
  redux/modules/searchValue.ts
  redux/modules/statuses.ts
  redux/store.ts
  utils/common/useInputSelect.ts
  utils/common/useReduxToolkit.ts
  utils/debates/debateroom/aws.ts
Labels: Modify, Delete, Update, Setting, Style

#100 Dev
  api/users.ts
  components/Header.module.scss
  components/Header.tsx
  components/common/modal/ChangePasswordModal.module.scss
  components/common/modal/ChangePasswordModal.tsx
  components/common/modal/CheckSignInModal.tsx
  components/common/modal/ConfirmModal.module.scss
  components/common/modal/SignInModal.module.scss
  components/common/modal/SignInModal.tsx
  components/debates/CreateOrEdit.module.scss
  components/debates/debate/Factcheck.tsx
  components/debates/debate/Factchecks.module.scss
  components/debates/debate/Vote.module.scss
  components/debates/debate/Vote.tsx
  components/debates/debate/index.module.scss
  components/debates/debate/index.tsx
  components/debates/debates/DebateCard.tsx
  components/debates/debates/DebatesCards.module.scss
  components/debates/debates/DebatesCards.tsx
  components/debates/debates/DebatesHeartList.tsx
  components/debates/debates/DebatesList.tsx
  components/debates/debates/Filters.module.scss
  components/debates/debates/Filters.tsx
  components/debates/debates/LikeBtn.module.scss
  components/debates/debates/LikeBtn.tsx
  package-lock.json
  package.json
  pages/_app.tsx
  pages/index.tsx
  pages/mypage/index.tsx
  pages/q&a/index.tsx
  pages/signin/index.tsx
  pages/signup/index.tsx
  redux/modules/categories.ts
  redux/modules/heartOrder.ts
  redux/modules/isHeartListOn.ts
  redux/modules/isSearchListOn.ts
  redux/modules/order.ts
  redux/modules/searchValue.ts
  redux/modules/statuses.ts
  redux/store.ts
  utils/common/useInputSelect.ts
  utils/common/useReduxToolkit.ts
  utils/debates/debateroom/aws.ts
Labels: Merge

#101 리드미 작성
  README.md
Labels: Docs

#102 Dev
  README.md
Labels: Merge

#103 단순 코드 개선
  components/debates/DebaterInfo.tsx
  package.json
  pages/404.tsx
  pages/[debateId].tsx
  pages/create.tsx
  pages/edit/[debateId].tsx
  pages/mypage/index.tsx
  pages/q&a/index.tsx
  pages/signin/index.tsx
  pages/signup/index.tsx
Labels: Modify, Delete, Fix

#105 로그인/로그아웃 시 좋아요 여부와 투표 여부 반영 문제 해결
  api/users.ts
  components/debates/debate/Vote.tsx
  components/debates/debate/index.tsx
  pages/signin/index.tsx
  utils/queries/hearts.ts
  utils/queries/users.ts
  utils/queries/votes.ts
Labels: Delete, Change, Update

#106 코드 정돈 및 개선
  api/comments.ts
  api/debates.ts
  api/factchecks.ts
  api/hearts.ts
  api/users.ts
  api/votes.ts
  components/Header.tsx
  components/common/modal/SignoutModal.tsx
  components/debates/CreateOrEdit.tsx
  components/debates/debate/Comments.tsx
  components/debates/debateroom/Buttons.tsx
  components/debates/debateroom/index.tsx
  components/debates/debates/DebatesCards.tsx
  components/debates/debates/DebatesHeartList.tsx
  components/debates/debates/DebatesList.tsx
  pages/mypage/index.tsx
  pages/signup/index.tsx
  types.ts
  utils/common/formatStrDate.ts
  utils/common/redirect.ts
  utils/common/removeSpace.ts
  utils/common/thousandDigit.ts
  utils/common/useInputSelect.ts
  utils/debates/checkFilters.ts
  utils/debates/debateroom/aws.ts
  utils/debates/debateroom/beep.ts
  utils/debates/debateroom/draw.ts
  utils/debates/debateroom/screenShare.ts
  utils/debates/debateroom/simple-peer.ts
  utils/debates/debateroom/toggle.ts
  utils/debates/debateroom/useAutoOff.ts
  utils/debates/debateroom/usePreventBack.ts
  utils/debates/debateroom/useSetInterval.ts
  utils/debates/debateroom/useSetRecorder.ts
  utils/debates/debateroom/webSocket.ts
  utils/queries/comments.ts
  utils/queries/debates.ts
  utils/queries/factchecks.ts
  utils/queries/hearts.ts
  utils/queries/index.ts
  utils/queries/users.ts
  utils/queries/votes.ts
Labels: Modify, Delete, Change, Update

#109 회원가입 개선
  api/users.ts
  pages/signup/index.tsx
Labels: Update

#110 SSR 도입
  pages/[debateId].tsx
  pages/_app.tsx
  pages/debateroom/[debateId].tsx
  pages/edit/[debateId].tsx
  pages/index.tsx
Labels: Add, Setting

#111 소소한 개선
  components/Footer.module.scss
  components/Footer.tsx
  components/Header.tsx
  pages/_app.tsx
  pages/signin/Signin.module.scss
  pages/signin/index.tsx
  public/images/logo/debate-ducks-logo-white.png
  utils/debates/debateroom/usePreventBack.ts
  utils/queries/debates.ts
Labels: Add, Change, Update, Style

#112 토론 목록 margin-bottom 변경
  components/debates/debates/DebatesCards.module.scss
  components/debates/debates/DebatesCards.tsx
Labels: Style

#113 소소한 개선
  components/common/btn/HomeAndTopBtn.module.scss
  components/debates/DebaterInfo.module.scss
  components/debates/debate/Comments.module.scss
  components/debates/debate/Factchecks.module.scss
  components/debates/debate/Vote.module.scss
  components/debates/debate/index.module.scss
  components/debates/debateroom/Buttons.module.scss
  components/debates/debateroom/Canvas.module.scss
  components/debates/debateroom/index.tsx
  components/debates/debates/DebateCard.module.scss
  components/debates/debates/DebatesCards.module.scss
  utils/debates/debateroom/useSetRecorder.ts
Labels: Modify, Update

#115 Q&A 페이지 제작
  pages/q&a/index.module.scss
  pages/q&a/index.tsx
  public/images/qna.jpg
Labels: Add, Style

#116 체험 토론 제작
  components/debates/CreateOrEdit.tsx
  components/debates/debateroom/experience/Button.tsx
  components/debates/debateroom/experience/Canvas.tsx
  components/debates/debateroom/experience/index.tsx
  package-lock.json
  package.json
  pages/debateroom/experience.tsx
  pages/q&a/index.tsx
  types.ts
Labels: Modify, Add, Update, Fix, Setting

#117 단순 주석 체계 수정
  api/comments.ts
  api/debates.ts
  api/factchecks.ts
  api/hearts.ts
  api/users.ts
  api/votes.ts
  components/debates/debateroom/Buttons.tsx
  components/debates/debateroom/index.tsx
  types.ts
  utils/common/formatStrDate.ts
  utils/common/removeSpace.ts
  utils/common/thousandDigit.ts
  utils/common/useInputSelect.ts
  utils/debates/checkFilters.ts
  utils/debates/debateroom/aws.ts
  utils/debates/debateroom/beep.ts
  utils/debates/debateroom/draw.ts
  utils/debates/debateroom/screenShare.ts
  utils/debates/debateroom/simple-peer.ts
  utils/debates/debateroom/toggle.ts
  utils/debates/debateroom/useAutoOff.ts
  utils/debates/debateroom/usePreventBack.ts
  utils/debates/debateroom/useSetInterval.ts
  utils/debates/debateroom/useSetRecorder.ts
  utils/debates/debateroom/webSocket.ts
  utils/queries/comments.ts
  utils/queries/debates.ts
  utils/queries/factchecks.ts
  utils/queries/hearts.ts
  utils/queries/users.ts
  utils/queries/votes.ts
Labels: Modify

#118 토큰 만료 시 삭제
  utils/queries/users.ts
Labels: Update

#119 에러 페이지 제작
  components/common/Error.module.scss
  components/common/Error.tsx
  components/common/Footer.module.scss
  components/common/Footer.tsx
  components/common/Header.module.scss
  components/common/Header.tsx
  pages/404.tsx
  pages/[debateId].tsx
  pages/_app.tsx
  pages/debateroom/[debateId].tsx
  pages/edit/[debateId].tsx
  pages/mypage/index.tsx
  public/images/duckling.png
Labels: Modify, Add, Update, Style

#121 수화 불일치 문제 해결 및 단순 코드 개선
  components/common/btn/HomeAndTopBtn.tsx
  pages/_app.tsx
Labels: Modify, Fix

#122 스크롤 위치 기억하기
  components/common/btn/HomeAndTopBtn.tsx
  package-lock.json
  package.json
  pages/[debateId].tsx
  pages/_app.tsx
  pages/index.tsx
  redux/modules/scrollMain.ts
  redux/store.ts
Labels: Modify, Add, Delete, Update, Setting

#124 깃 허브 액션 삭제
  .github/workflows/main.yml
Labels: Delete

#127 Main to Dev
  components/common/modal/SignOutModal.tsx
  components/debates/debates/DebatesCards.module.scss
Labels: Pull

#129 사파리 브라우저에서 발생하는 문제 해결
  components/debates/debateroom/Buttons.module.scss
  components/debates/debateroom/Buttons.tsx
  components/debates/debateroom/experience/Button.tsx
  components/debates/debateroom/experience/index.tsx
  components/debates/debateroom/index.module.scss
  components/debates/debateroom/index.tsx
  pages/q&a/index.tsx
  public/images/arrow.png
  styles/globals.scss
  utils/debates/debateroom/draw.ts
  utils/debates/debateroom/useSetRecorder.ts
Labels: Modify, Update, Fix, Style

#130 소소한 문제들 수정
  components/common/Error.tsx
  components/common/modal/ConfirmModal.module.scss
  components/debates/debate/index.tsx
  components/debates/debateroom/experience/index.tsx
  components/debates/debates/DebatesList.tsx
  styles/globals.scss
  types.ts
  utils/debates/debateroom/useSetRecorder.ts
Labels: Modify, Update, Fix, Style

#131 v2.1.1
  README.md
  components/common/Error.tsx
  components/common/modal/ConfirmModal.module.scss
  components/debates/debate/index.tsx
  components/debates/debateroom/Buttons.module.scss
  components/debates/debateroom/Buttons.tsx
  components/debates/debateroom/experience/Button.tsx
  components/debates/debateroom/experience/index.tsx
  components/debates/debateroom/index.module.scss
  components/debates/debateroom/index.tsx
  components/debates/debates/DebatesList.tsx
  pages/q&a/index.tsx
  public/images/arrow.png
  styles/globals.scss
  types.ts
  utils/debates/debateroom/draw.ts
  utils/debates/debateroom/useSetRecorder.ts
Labels: Merge

#132 정적 배포로 변경
  components/debates/debate/EditAndDelete.tsx
  components/debates/debate/index.tsx
  components/debates/debateroom/Buttons.tsx
  components/debates/debateroom/index.tsx
  pages/debate.tsx
  pages/debateroom/index.tsx
  pages/edit/index.tsx
  utils/debates/debateroom/webSocket.ts
  utils/queries/debates.ts
Labels: Delete, Change

#134 v2.1.2
  README.md
  components/debates/debate/EditAndDelete.tsx
  components/debates/debate/index.tsx
  components/debates/debateroom/Buttons.tsx
  components/debates/debateroom/index.tsx
  components/debates/debates/DebateCard.tsx
  package.json
  pages/debate.tsx
  pages/debateroom/index.tsx
  pages/edit/index.tsx
  pages/mypage/MyPage.module.scss
  pages/mypage/index.tsx
  pages/signin/Signin.module.scss
  pages/signup/Signup.module.scss
  pages/signup/index.tsx
  utils/debates/debateroom/webSocket.ts
  utils/queries/debates.ts
Labels: Merge

#135 Main to Dev
  .github/workflows/main.yml
Labels: Pull

#136 소소한 개선들
  pages/_app.tsx
  utils/queries/debates.ts
  utils/queries/hearts.ts
Labels: Modify, Delete, Update, Fix

#137 토론 카드 목록 배치 문제 해결
  components/debates/debates/DebateCard.module.scss
  components/debates/debates/DebatesCards.module.scss
  components/debates/debates/DebatesCards.tsx
Labels: Update, Style

#138 v2.1.2
  README.md
  components/debates/debates/DebateCard.module.scss
  components/debates/debates/DebatesCards.module.scss
  components/debates/debates/DebatesCards.tsx
  pages/_app.tsx
  utils/queries/debates.ts
  utils/queries/hearts.ts
Labels: Merge

#142 치명적인 문제들 해결
  components/debates/debateroom/index.tsx
  components/debates/debates/LikeBtn.tsx
  pages/_app.tsx
  pages/debate.tsx
  utils/debates/debateroom/useSetRecorder.ts
Labels: Fix

#143 v2.1.3
  README.md
  pages/_app.tsx
  pages/debate.tsx
  utils/debates/debateroom/useSetRecorder.ts
Labels: Merge
