Repository SuSang-YuHee/Debate-Ducks-Client, pull requests merged in 2022-07, with the labels that each got.

#29 토론 시 남은 시간 생략 및 경고음
  components/debateroom/Buttons.tsx
  components/debateroom/Canvas.tsx
  components/debateroom/Room.tsx
  components/debateroom/types.ts
  components/debateroom/utils/beep.ts
  components/debateroom/utils/draw.ts
  components/debateroom/utils/screenShare.ts
  components/debateroom/utils/toggle.ts
  components/debateroom/utils/webSocket.ts
Labels: Modify, Update

#30 경고음 시간 변경
  components/debateroom/utils/webSocket.ts
Labels: Change

#32 녹화 및 임시 다운로드 기능
  components/debateroom/Buttons.tsx
  components/debateroom/Canvas.tsx
  components/debateroom/Room.tsx
  components/debateroom/types.ts
  components/debateroom/utils/draw.ts
  components/debateroom/utils/screenShare.ts
  components/debateroom/utils/simple-peer.ts
  components/debateroom/utils/toggle.ts
  components/debateroom/utils/upload.ts
  components/debateroom/utils/useAutoOff.ts
  components/debateroom/utils/useSetInterval.ts
  components/debateroom/utils/useSetRecorder.ts
  components/debateroom/utils/webSocket.ts
  pages/debates/debateroom/[debateId].tsx
Labels: Modify, Add, Delete, Change, Update, Fix

#34 회원가입 기능 추가
  package-lock.json
  package.json
  pages/signup/index.tsx
  styles/Signup.module.scss
Labels: Add, Update

#35 토론 게시물 CRUD
  api/debates.ts
  api/hello.ts
  components/common/modal/ConfirmModal.tsx
  components/common/modal/ErrorAndCheckModal.tsx
  components/debates/CreateOrEdit.tsx
  components/debates/debate/AfterDebate.tsx
  components/debates/debate/Comments.tsx
  components/debates/debate/DebaterInfo.tsx
  components/debates/debate/EditAndDelete.tsx
  components/debates/debate/index.tsx
  components/debates/debateroom/Buttons.tsx
  components/debates/debateroom/Canvas.tsx
  components/debates/debateroom/index.tsx
  components/debates/debateroom/types.ts
  components/debates/debateroom/utils/beep.ts
  components/debates/debateroom/utils/draw.ts
  components/debates/debateroom/utils/screenShare.ts
  components/debates/debateroom/utils/simple-peer.ts
  components/debates/debateroom/utils/toggle.ts
  components/debates/debateroom/utils/upload.ts
  components/debates/debateroom/utils/useAutoOff.ts
  components/debates/debateroom/utils/useSetInterval.ts
  components/debates/debateroom/utils/useSetRecorder.ts
  components/debates/debateroom/utils/webSocket.ts
  package-lock.json
  package.json
  pages/_app.tsx
  pages/debates/[debateId].tsx
  pages/debates/create.tsx
  pages/debates/debate/[debateId].tsx
  pages/debates/debateroom/[debateId].tsx
  pages/debates/edit/[debateId].tsx
  types.ts
  utils/debates/createOrEdit.ts
  utils/index.ts
  utils/queries/debates.ts
  utils/redirect.ts
  utils/useInputSelect.ts
Labels: Modify, Add, Setting

#36 로그인 기능 추가
  pages/signin/index.tsx
Labels: Modify, Add

#37 회원가입 유효성 검사 개선
  pages/signup/index.tsx
Labels: Add, Update

#38 토론 게시물 CRUD 개선
  api/debates.ts
  components/debates/CreateOrEdit.tsx
  components/debates/debate/AfterDebate.tsx
  components/debates/debate/DebaterInfo.tsx
  components/debates/debate/index.tsx
  package-lock.json
  pages/debates/[debateId].tsx
  pages/debates/create.tsx
  pages/debates/edit/[debateId].tsx
  types.ts
  utils/queries/debates.ts
Labels: Change, Update

#39 좋아요 기능 추가
  api/heart.ts
  components/debates/debate/index.tsx
  types.ts
  utils/queries/debates.ts
  utils/queries/heart.ts
Labels: Add

#41 Feat/factcheck
  api/factchecks.ts
  components/common/modal/ErrAndCheckModal.tsx
  components/debates/CreateOrEdit.tsx
  components/debates/debate/AfterDebate.tsx
  components/debates/debate/DebaterInfo.tsx
  components/debates/debate/EditAndDelete.tsx
  components/debates/debate/Factchecks.tsx
  components/debates/debate/Vote.tsx
  components/debates/debate/index.tsx
  pages/debates/create.tsx
  pages/debates/edit/[debateId].tsx
  types.ts
  utils/queries/debates.ts
  utils/queries/factchecks.ts
  utils/queries/hearts.ts
  utils/queries/votes.ts
Labels: Modify, Add, Fix

#45 유저 정보 조회 리액트 쿼리 적용
  api/users.ts
  pages/_app.tsx
  pages/debates/[debateId].tsx
  pages/signin/index.tsx
  types.ts
  utils/queries/debates.ts
  utils/queries/factchecks.ts
  utils/queries/hearts.ts
  utils/queries/index.ts
  utils/queries/users.ts
  utils/queries/votes.ts
Labels: Modify, Add

#46 에러 모달을 에러 메시지로 변경
  components/common/modal/ErrAndCheckModal.tsx
  components/debates/CreateOrEdit.tsx
  components/debates/debate/DebaterInfo.tsx
  components/debates/debate/EditAndDelete.tsx
  components/debates/debate/Factchecks.tsx
  components/debates/debate/Vote.tsx
  components/debates/debate/index.tsx
  package-lock.json
  package.json
  pages/_app.tsx
  pages/debates/[debateId].tsx
  pages/debates/create.tsx
  pages/debates/edit/[debateId].tsx
  utils/debates/createOrEdit.ts
  utils/queries/debates.ts
  utils/queries/factchecks.ts
  utils/queries/hearts.ts
  utils/queries/votes.ts
Labels: Change

#47 댓글 기능 추가
  api/comments.ts
  components/debates/debate/Comments.tsx
  package-lock.json
  package.json
  pages/_app.tsx
  types.ts
  utils/formatStrDate.ts
  utils/queries/comments.ts
  utils/queries/index.ts
  utils/removeSpace.ts
Labels: Add, Change

#48 정렬 및 체크박스 컴포넌트
  api/comments.ts
  components/debates/CheckBox.tsx
  components/debates/CreateOrEdit.tsx
  components/debates/debate/Comments.tsx
  components/debates/debate/DebaterInfo.tsx
  components/debates/debate/EditAndDelete.tsx
  components/debates/debate/Factchecks.tsx
  components/debates/debate/index.tsx
  pages/debates/[debateId].tsx
  pages/debates/create.tsx
  pages/debates/edit/[debateId].tsx
  pages/debates/index.tsx
  utils/constant.ts
  utils/queries/comments.ts
  utils/useInputSelect.ts
Labels: Modify, Add, Update

#49 토론 목록 조회
  api/comments.ts
  api/debates.ts
  api/users.ts
  components/debates/CreateOrEdit.tsx
  components/debates/debate/Comments.tsx
  components/debates/debate/DebaterInfo.tsx
  components/debates/debate/Factchecks.tsx
  components/debates/debates/CheckBox.tsx
  components/debates/debates/DebatesHeartList.tsx
  components/debates/debates/DebatesList.tsx
  pages/debates/create.tsx
  pages/debates/edit/[debateId].tsx
  pages/debates/index.tsx
  types.ts
  utils/common/constant.ts
  utils/common/formatStrDate.ts
  utils/common/redirect.ts
  utils/common/removeSpace.ts
  utils/common/useInputSelect.ts
  utils/debates/checkCategory.ts
  utils/queries/comments.ts
  utils/queries/debates.ts
  utils/queries/users.ts
Labels: Modify, Add, Delete, Change, Update, Fix

#50 초기 스타일, 메타 정보 및 파비콘 설정
  package-lock.json
  package.json
  pages/_app.tsx
  pages/debates/index.tsx
  pages/index.tsx
  public/favicon.ico
  public/vercel.svg
  styles/Home.module.css
  styles/globals.css
  styles/globals.scss
Labels: Modify, Delete, Setting

#51 색상 변수 공용 설정
  components/debates/debateroom/utils/draw.ts
  styles/globals.scss
  styles/variable.scss
  utils/common/constant.ts
Labels: Style

#52 토론 목록 필터 스타일 작업 및 디테일 마무리
  components/debates/debates/CheckBox.tsx
  components/debates/debates/Filters.module.scss
  components/debates/debates/Filters.tsx
  package-lock.json
  package.json
  pages/debates/index.tsx
  styles/variable.scss
  utils/common/constant.ts
Labels: Modify, Delete, Change, Style

#53 좋아요 목록만 보기 버튼 및 공용 모달
  components/common/modal/ConfirmModal.module.scss
  components/common/modal/ConfirmModal.tsx
  components/debates/debates/Filters.module.scss
  components/debates/debates/Filters.tsx
  components/debates/debates/LikeBtn.module.scss
  components/debates/debates/LikeBtn.tsx
  pages/_app.tsx
  pages/_document.tsx
  pages/debates/index.tsx
  styles/variable.scss
Labels: Modify, Change, Fix, Style

#57 병합 과정 괄호 누락 에러 수정
  api/users.ts
Labels: Fix

#58 토론 목록 스타일 작업 및 기능 디테일 처리
  api/debates.ts
  components/common/modal/ConfirmModal.module.scss
  components/common/modal/SignInModal.module.scss
  components/debates/debate/index.tsx
  components/debates/debates/DebateCard.module.scss
  components/debates/debates/DebateCard.tsx
  components/debates/debates/Debater.module.scss
  components/debates/debates/Debater.tsx
  components/debates/debates/DebatesContainer.module.scss
  components/debates/debates/DebatesContainer.tsx
  components/debates/debates/DebatesHeartList.tsx
  components/debates/debates/DebatesList.tsx
  components/debates/debates/Filters.module.scss
  components/debates/debates/LikeBtn.module.scss
  pages/_document.tsx
  pages/debates/index.tsx
  public/images/categories/0.jpg
  public/images/categories/1.jpg
  public/images/categories/2.jpg
  public/images/categories/3.jpg
  public/images/categories/4.jpg
  public/images/categories/5.jpg
  public/images/categories/6.jpg
  public/images/categories/7.jpg
  public/images/categories/8.jpg
  public/images/categories/9.jpg
  public/images/profiles/default-gray.png
  styles/globals.scss
  styles/variable.scss
  types.ts
  utils/debates/checkCategory.ts
  utils/debates/checkFilters.ts
  utils/debates/createOrEdit.ts
  utils/queries/hearts.ts
Labels: Change, Update, Fix, Style

#59 네트워크 에러 시 에러 메시지 타입 문제 해결
  api/users.ts
  components/debates/debates/DebatesContainer.tsx
  utils/queries/comments.ts
  utils/queries/debates.ts
  utils/queries/factchecks.ts
  utils/queries/hearts.ts
  utils/queries/votes.ts
Labels: Fix, Style

#61 토론 생성 및 수정 스타일 적용 및 개선
  api/users.ts
  components/common/modal/ConfirmModal.module.scss
  components/common/modal/ConfirmModal.tsx
  components/common/modal/SignInModal.module.scss
  components/debates/CreateOrEdit.module.scss
  components/debates/CreateOrEdit.tsx
  components/debates/debates/DebateCard.module.scss
  components/debates/debates/DebatesContainer.module.scss
  components/debates/debates/Filters.module.scss
  pages/404.tsx
  pages/debates/create.tsx
  pages/debates/edit/[debateId].tsx
  styles/variable.scss
  utils/debates/createOrEdit.ts
  utils/queries/comments.ts
  utils/queries/debates.ts
  utils/queries/factchecks.ts
  utils/queries/hearts.ts
  utils/queries/votes.ts
Labels: Modify, Delete, Update, Style
